### ISSUE TITLE
Update to add support for Layout Management

### ISSUE THREAD

**Issue by n0toose** [HaikuArchives/Toner#4]
Although this is a quite simple and small application, there's no reason as to why it shouldn't use the Layout API. Doing so would make extending the set of features the application provides in the future easier, without having to break the entire application. Also, the margin between the top side and the first element is disproportionally bigger than the margin between the bottom side and the second element.

![image](https://user-images.githubusercontent.com/30193966/71812597-416f9400-3080-11ea-8170-9465b10d47c9.png)

Reference: https://www.haiku-os.org/docs/api/layout_intro.html

**Comment by trungnt2910** [comment]
I'm taking this.

**Comment by scottmc** [comment]
fixed with 9ca394c2231c5a213a48335cf13b271756bed67c thanks @trungnt2910
