### ISSUE TITLE
SoundPlayer missing

### ISSUE THREAD

**Issue by Huzzai** [HaikuArchives/Toner#6]
I am running with difficulties finding the right library which not included in libraries folder.
Soundplayer.h

can you upload it? thank

**Comment by korli** [comment]
it's a system header: https://git.haiku-os.org/haiku/tree/headers/os/media/SoundPlayer.h

**Comment by korli** [comment]
See Haikuports recipe if you need to build: https://github.com/haikuports/haikuports/blob/master/haiku-apps/toner/toner-1.0.0.recipe
